/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["get_api_v1_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_api_v1_snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Status */
        get: operations["get_api_v1_model_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visualizers/classrooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Classroom Demo */
        get: operations["get_api_v1_visualizers_classrooms"];
        put?: never;
        /** Act Classroom Demo */
        post: operations["post_api_v1_visualizers_classrooms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hardware */
        get: operations["get_api_v1_hardware"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Hardware Connect */
        post: operations["post_api_v1_hardware_connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Hardware Disconnect */
        post: operations["post_api_v1_hardware_disconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visualizers/hospital": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hospital Demo */
        get: operations["get_api_v1_visualizers_hospital"];
        put?: never;
        /** Act Hospital Demo */
        post: operations["post_api_v1_visualizers_hospital"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Activity Observation */
        post: operations["post_api_v1_activity_observations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay Action */
        post: operations["post_api_v1_replay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Rfid Scan */
        post: operations["post_api_v1_rfid_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Capacity */
        post: operations["post_api_v1_simulation_capacity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/classroom-load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Classroom Load */
        post: operations["post_api_v1_simulation_classroom_load"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/feeder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Feeder */
        post: operations["post_api_v1_simulation_feeder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/allocation/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Allocation Policy */
        get: operations["get_api_v1_allocation_policy"];
        /** Change Allocation Policy */
        put: operations["put_api_v1_allocation_policy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/electrical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Electrical Study */
        post: operations["post_api_v1_studies_electrical"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hardware Ack */
        post: operations["post_api_v1_hardware_ack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["get_api_v1_history_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Records */
        get: operations["get_api_v1_history_records"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityObservationRequest */
        ActivityObservationRequest: {
            /** Classroom Id */
            classroom_id: string;
            /** Temperature C */
            temperature_c?: number | null;
            /** Humidity Pct */
            humidity_pct?: number | null;
            /** Co2 Ppm */
            co2_ppm?: number | null;
            /** Humidity Ratio */
            humidity_ratio?: number | null;
            /** Observed At */
            observed_at: string;
            /** Source */
            source: string;
        };
        /** ActivityObservationResponse */
        ActivityObservationResponse: {
            /** Accepted */
            accepted: boolean;
            /** Applied */
            applied: boolean;
            /** Revision */
            revision: number;
            activity: components["schemas"]["ActivitySnapshot"];
        };
        /** ActivitySnapshot */
        ActivitySnapshot: {
            /** State */
            state: string;
            /** Score */
            score?: number | null;
            /** Reason */
            reason: string;
            /** Source */
            source?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Model Version */
            model_version: string;
            /** Priority */
            priority: string;
            /** Evidence */
            evidence?: {
                [key: string]: number | null;
            } | null;
            /** Raw State */
            raw_state?: string | null;
            /** Guard */
            guard?: string | null;
        };
        /** AllocationPolicy */
        AllocationPolicy: {
            /**
             * Name
             * @default activity_first
             * @enum {string}
             */
            name: "activity_first" | "water_first";
            /**
             * Version
             * @default allocation-v1
             * @constant
             */
            version: "allocation-v1";
            /**
             * Fairness Weight
             * @default 0
             */
            fairness_weight: number;
            /**
             * Switching Penalty
             * @default 1
             */
            switching_penalty: number;
        };
        /** AllocationPolicyResponse */
        AllocationPolicyResponse: {
            /**
             * Name
             * @enum {string}
             */
            name: "activity_first" | "water_first";
            /**
             * Version
             * @constant
             */
            version: "allocation-v1";
            /** Fairness Weight */
            fairness_weight: number;
            /** Switching Penalty */
            switching_penalty: number;
        };
        /** AllocationPolicyUpdateResponse */
        AllocationPolicyUpdateResponse: {
            policy: components["schemas"]["AllocationPolicyResponse"];
            receipt: components["schemas"]["CommandReceipt"];
        };
        /** AllocationSnapshot */
        AllocationSnapshot: {
            /** Explanation */
            explanation?: {
                [key: string]: unknown;
            };
            /** Objective */
            objective: string;
            /** Critical Shortfall W */
            critical_shortfall_w: number;
            /** Served W */
            served_w: number;
            /** Baseline Mask */
            baseline_mask: number;
            safety?: components["schemas"]["SafetySnapshot"] | null;
        };
        /** BoardAStatus */
        BoardAStatus: {
            /** Boot */
            boot?: number | null;
            /** Reader Ok */
            reader_ok?: boolean | null;
            /** Radio Configured */
            radio_configured?: boolean | null;
        };
        /** BoardBStatus */
        BoardBStatus: {
            /** Online */
            online: boolean;
            /** Boot */
            boot?: number | null;
            /** Radio Ready */
            radio_ready: boolean;
        };
        /** CapacityChangeRequest */
        CapacityChangeRequest: {
            /** Capacity W */
            capacity_w: number;
        };
        /** CapacityChangeResponse */
        CapacityChangeResponse: {
            /** Accepted */
            accepted: boolean;
            /** New Capacity W */
            new_capacity_w: number;
            /** Control Revision */
            control_revision: number;
        };
        /** ClassroomDemoAction */
        ClassroomDemoAction: {
            /**
             * Action
             * @enum {string}
             */
            action: "scan" | "unscan" | "set_capacity" | "normal" | "overload" | "reset" | "replay_pause" | "replay_resume" | "replay_step";
            /** Classroom Id */
            classroom_id?: ("CR1" | "CR2" | "CR3") | null;
            /** Capacity W */
            capacity_w?: number | null;
        };
        /** ClassroomDemoLoadResponse */
        ClassroomDemoLoadResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Watts */
            watts: number;
            /** Essential */
            essential: boolean;
            /** Served */
            served: boolean;
            /** Reason */
            reason: string;
        };
        /** ClassroomDemoResponse */
        ClassroomDemoResponse: {
            contract: components["schemas"]["CrossRouteContract"];
            site?: components["schemas"]["SiteIdentityResponse"] | null;
            /** Published Revision */
            published_revision?: number | null;
            /** Capacity W */
            capacity_w: number;
            /** Capacity Range W */
            capacity_range_w: number[];
            /** Classroom Limit W */
            classroom_limit_w: number;
            /** Campus Limit W */
            campus_limit_w?: number | null;
            /** Effective Capacity W */
            effective_capacity_w: number;
            /**
             * Limited By
             * @enum {string}
             */
            limited_by: "classroom limit" | "campus feeder B";
            /** Requested W */
            requested_w: number;
            /** Served W */
            served_w: number;
            /** Shortfall W */
            shortfall_w: number;
            /** Selected Classroom Id */
            selected_classroom_id?: string | null;
            /** Scanned Classroom Ids */
            scanned_classroom_ids: string[];
            /** Priority Order */
            priority_order: string[];
            /** Rooms */
            rooms: components["schemas"]["ClassroomDemoRoomResponse"][];
            /**
             * Mode
             * @constant
             */
            mode: "SIMULATED";
            safety: components["schemas"]["SafetySnapshot"];
            /** Edges */
            edges?: components["schemas"]["PowerEdge"][];
            /** Generated At */
            generated_at?: string | null;
            command?: components["schemas"]["CommandReceipt"] | null;
            hardware?: components["schemas"]["HardwareStatusResponse"] | null;
            model: components["schemas"]["VisualizerModelStatus"];
            replay: components["schemas"]["VisualizerReplay"];
            /** Policy */
            policy: string;
        };
        /** ClassroomDemoRoomResponse */
        ClassroomDemoRoomResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Rfid Active */
            rfid_active: boolean;
            /** Priority Rank */
            priority_rank?: number | null;
            activity: components["schemas"]["VisualizerActivity"];
            /** Loads */
            loads: components["schemas"]["ClassroomDemoLoadResponse"][];
        };
        /** ClassroomInfo */
        ClassroomInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Service Id */
            service_id: string;
            /** Rfid Card Registered */
            rfid_card_registered: boolean;
            /** Led Bit */
            led_bit: number;
            /** Load Event Active */
            load_event_active: boolean;
        };
        /** ClassroomLoadRequest */
        ClassroomLoadRequest: {
            /** Classroom Id */
            classroom_id: string;
            /** Active */
            active: boolean;
        };
        /** ClassroomLoadResponse */
        ClassroomLoadResponse: {
            /** Accepted */
            accepted: boolean;
            /** Classroom Id */
            classroom_id: string;
            /** Load Event Active */
            load_event_active: boolean;
        };
        /** ClassroomZone */
        ClassroomZone: {
            /** Active Classroom Id */
            active_classroom_id?: string | null;
            /** Recent Rfid Scan */
            recent_rfid_scan?: string | null;
            /** @default NOT_CONNECTED */
            rfid_reader_status: components["schemas"]["RfidReaderStatus"];
            /** Classrooms */
            classrooms: components["schemas"]["ClassroomInfo"][];
        };
        /** CommandReceipt */
        CommandReceipt: {
            /** Command Id */
            command_id: string;
            /** Name */
            name: string;
            /** Run Id */
            run_id: string;
            /** Applied Revision */
            applied_revision: number;
        };
        /** ControlLoopHealth */
        ControlLoopHealth: {
            /** Running */
            running: boolean;
            /** Period S */
            period_s: number;
            /** Tick Count */
            tick_count: number;
            /** Missed Ticks */
            missed_ticks: number;
            /** Errors */
            errors: number;
            /** Last Error */
            last_error?: string | null;
            /** Last Tick Age S */
            last_tick_age_s?: number | null;
            /** Last Tick At */
            last_tick_at?: string | null;
        };
        /** CrossRouteContract */
        CrossRouteContract: {
            identity: components["schemas"]["RunIdentity"];
            campus_totals?: components["schemas"]["ScopeTotals"] | null;
            /**
             * Zone Totals
             * @default {}
             */
            zone_totals: {
                [key: string]: components["schemas"]["ScopeTotals"];
            };
        };
        /** DiagnosticAbstentionResponse */
        DiagnosticAbstentionResponse: {
            /** Asset Id */
            asset_id: string;
            /** Reason */
            reason: string;
            /** Details */
            details: string;
            /** Missing Sensors */
            missing_sensors: string[];
            /** Contradictory Readings */
            contradictory_readings: string[];
            /** Indistinguishable Candidates */
            indistinguishable_candidates: string[];
            /** Next Check Needed */
            next_check_needed: string;
        };
        /** DiagnosticHypothesisResponse */
        DiagnosticHypothesisResponse: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Asset Id */
            asset_id: string;
            /** Cause */
            cause: string;
            /** Severity */
            severity: string;
            /** Evidence Score */
            evidence_score: number;
            /** Sufficiency */
            sufficiency: string;
            /** Supporting Evidence */
            supporting_evidence: string[];
            /** Contradicting Evidence */
            contradicting_evidence: string[];
            /** Recommendation */
            recommendation: string;
        };
        /** ElectricalInput */
        ElectricalInput: {
            /**
             * Topology Version
             * @default radial-400v-v1
             * @constant
             */
            topology_version: "radial-400v-v1";
            /**
             * Balanced
             * @default true
             */
            balanced: boolean;
            /**
             * Load A W
             * @default 6000
             */
            load_a_w: number;
            /**
             * Load B W
             * @default 8000
             */
            load_b_w: number;
            /**
             * Source On
             * @default true
             */
            source_on: boolean;
            /**
             * Feeder A Closed
             * @default true
             */
            feeder_a_closed: boolean;
            /**
             * Feeder B Closed
             * @default true
             */
            feeder_b_closed: boolean;
            /**
             * Power Factor
             * @default 0.95
             */
            power_factor: number;
            /**
             * Resistance Ohm
             * @default 0.04
             */
            resistance_ohm: number;
            /**
             * Reactance Ohm
             * @default 0.015
             */
            reactance_ohm: number;
        };
        /** ElectricalResult */
        ElectricalResult: {
            /**
             * Mode
             * @default balanced_ac_study
             * @constant
             */
            mode: "balanced_ac_study";
            /**
             * Topology Version
             * @default radial-400v-v1
             */
            topology_version: string;
            /** Engine */
            engine: string;
            /** Engine Version */
            engine_version?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "converged" | "deenergized" | "failed" | "unavailable";
            /** Converged */
            converged: boolean;
            /**
             * Restoration Authorized
             * @default false
             * @constant
             */
            restoration_authorized: false;
            /** Observed At */
            observed_at: string;
            inputs: components["schemas"]["ElectricalInput"];
            /** Units */
            units: {
                [key: string]: string;
            };
            /** Buses */
            buses: {
                [key: string]: {
                    [key: string]: number | boolean | null;
                };
            };
            /** Branches */
            branches: {
                [key: string]: {
                    [key: string]: number | boolean | null;
                };
            };
            /** Source P W */
            source_p_w?: number | null;
            /** Source Q Var */
            source_q_var?: number | null;
            /** Loss W */
            loss_w?: number | null;
            /** Power Balance Residual W */
            power_balance_residual_w?: number | null;
            /** Reason */
            reason?: string | null;
            /**
             * Provenance
             * @default SIMULATED_AC_SOLVER; synthetic engineering parameters
             */
            provenance: string;
        };
        /** ElectricalStudyResponse */
        ElectricalStudyResponse: {
            /** Site */
            site: {
                [key: string]: unknown;
            };
            result: components["schemas"]["ElectricalResult"];
            /** Diagnosis */
            diagnosis: {
                [key: string]: unknown;
            };
        };
        /** FacilityZones */
        FacilityZones: {
            hospital: components["schemas"]["HospitalZone"];
            classroom: components["schemas"]["ClassroomZone"];
        };
        /** FaultDiagnosis */
        FaultDiagnosis: {
            /** Has Fault */
            has_fault: boolean;
            /** Diagnosis */
            diagnosis: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Hypotheses */
            hypotheses?: {
                [key: string]: unknown;
            }[];
            /** Affected Assets */
            affected_assets?: string[];
            /** Supply Constraint */
            supply_constraint?: string | null;
        };
        /** FeederChangeRequest */
        FeederChangeRequest: {
            /** Feeder */
            feeder: string;
            /** Available */
            available: boolean;
        };
        /** FeederChangeResponse */
        FeederChangeResponse: {
            /** Accepted */
            accepted: boolean;
            /** Feeder */
            feeder: string;
            /** Available */
            available: boolean;
            /** Control Revision */
            control_revision: number;
        };
        /** GatewayConnect */
        GatewayConnect: {
            /** Port */
            port: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareAckRequest */
        HardwareAckRequest: {
            /** Device Boot */
            device_boot: string;
            /** Sequence */
            sequence: number;
            /** Session */
            session: string;
            /** Confirmed Mask */
            confirmed_mask: number;
            /** Provenance */
            provenance: string;
        };
        /** HardwareAckResponse */
        HardwareAckResponse: {
            /** Accepted */
            accepted: boolean;
        };
        /** HardwareEvent */
        HardwareEvent: {
            /** Event */
            event: number;
            /** Action */
            action: string;
            /** Room */
            room?: string | null;
            /** Accepted */
            accepted: boolean;
        };
        /**
         * HardwareLinkStatus
         * @enum {string}
         */
        HardwareLinkStatus: "NOT_CONNECTED" | "CONNECTED" | "ERROR";
        /** HardwareStatusResponse */
        HardwareStatusResponse: {
            /**
             * Link
             * @enum {string}
             */
            link: "NOT_CONFIGURED" | "CONNECTING" | "SYNCING" | "CONNECTED" | "STALE";
            /** Commanded Mask */
            commanded_mask?: number | null;
            /** Confirmed Mask */
            confirmed_mask?: number | null;
            /** Led Confirmed */
            led_confirmed?: boolean | null;
            board_a?: components["schemas"]["BoardAStatus"] | null;
            board_b?: components["schemas"]["BoardBStatus"] | null;
            /** Session */
            session?: number | string | null;
            /** Last Radio Result */
            last_radio_result?: string | null;
            /** Recent Events */
            recent_events?: components["schemas"]["HardwareEvent"][];
            /** Recent Status */
            recent_status?: string[];
            /** Port Error */
            port_error?: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            control_loop: components["schemas"]["ControlLoopHealth"];
            storage: components["schemas"]["StorageHealth"];
            /** Status */
            status: string;
            /** Application */
            application: string;
        };
        /** HistoryDecisionPayload */
        HistoryDecisionPayload: {
            snapshot: components["schemas"]["SystemSnapshot"];
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Policy */
            policy: {
                [key: string]: unknown;
            };
            /** Model */
            model: {
                [key: string]: unknown;
            };
            /** Event Ids */
            event_ids: string[];
            /** Trail */
            trail: {
                [key: string]: unknown;
            };
        };
        /** HistoryDecisionRecord */
        HistoryDecisionRecord: {
            /** Seq */
            seq: number;
            /** Record Id */
            record_id: string;
            /** Site Id */
            site_id: string;
            /** Run Id */
            run_id: string;
            /** Timestamp */
            timestamp: string;
            /** Revision */
            revision: number;
            /** Provenance */
            provenance: string;
            /**
             * Kind
             * @constant
             */
            kind: "decision";
            payload: components["schemas"]["HistoryDecisionPayload"];
        };
        /** HistoryEventPayload */
        HistoryEventPayload: {
            event: components["schemas"]["SystemEvent"];
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            };
        };
        /** HistoryEventRecord */
        HistoryEventRecord: {
            /** Seq */
            seq: number;
            /** Record Id */
            record_id: string;
            /** Site Id */
            site_id: string;
            /** Run Id */
            run_id: string;
            /** Timestamp */
            timestamp: string;
            /** Revision */
            revision: number;
            /** Provenance */
            provenance: string;
            /**
             * Kind
             * @constant
             */
            kind: "event";
            payload: components["schemas"]["HistoryEventPayload"];
        };
        /** HistoryPageResponse */
        HistoryPageResponse: {
            /** Items */
            items: (components["schemas"]["HistoryEventRecord"] | components["schemas"]["HistoryDecisionRecord"] | components["schemas"]["HistoryTelemetryRecord"])[];
            /** Next Cursor */
            next_cursor?: number | null;
            /** Retention Gap */
            retention_gap: boolean;
            /** Pruned Through */
            pruned_through: number;
        };
        /** HistoryRunResponse */
        HistoryRunResponse: {
            /** Site Id */
            site_id: string;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at: string;
            /** Pruned Through */
            pruned_through: number;
        };
        /** HistoryRunsResponse */
        HistoryRunsResponse: {
            /** Current Run Id */
            current_run_id: string;
            /** Runs */
            runs: components["schemas"]["HistoryRunResponse"][];
        };
        /** HistoryTelemetryPayload */
        HistoryTelemetryPayload: {
            /** State Generated At */
            state_generated_at: string;
            /** Capacity */
            capacity: number;
            /** Demand */
            demand: number;
            /** Servedcount */
            servedCount: number;
            /** Shedcount */
            shedCount: number;
        };
        /** HistoryTelemetryRecord */
        HistoryTelemetryRecord: {
            /** Seq */
            seq: number;
            /** Record Id */
            record_id: string;
            /** Site Id */
            site_id: string;
            /** Run Id */
            run_id: string;
            /** Timestamp */
            timestamp: string;
            /** Revision */
            revision: number;
            /** Provenance */
            provenance: string;
            /**
             * Kind
             * @constant
             */
            kind: "telemetry";
            payload: components["schemas"]["HistoryTelemetryPayload"];
        };
        /** HospitalDemoAction */
        HospitalDemoAction: {
            /** Action */
            action?: ("scan" | "unscan" | "set_capacity" | "normal" | "overload" | "reset" | "replay_pause" | "replay_resume" | "replay_step") | null;
            /** Zone Id */
            zone_id?: ("ICU" | "Theatre" | "Wards") | null;
            /** Capacity W */
            capacity_w?: number | null;
            /** Scenario */
            scenario?: ("normal" | "overload" | "cooling_failure" | "upstream_loss" | "missing_sensor") | null;
        };
        /** HospitalDemoResponse */
        HospitalDemoResponse: {
            contract: components["schemas"]["CrossRouteContract"];
            site?: components["schemas"]["SiteIdentityResponse"] | null;
            /**
             * Mode
             * @constant
             */
            mode: "SIMULATED";
            /** Transformers */
            transformers: components["schemas"]["HospitalDemoTransformerResponse"][];
            /** Summary */
            summary?: string | null;
            /** Capacity W */
            capacity_w?: number | null;
            /** Capacity Range W */
            capacity_range_w?: number[] | null;
            /** Requested W */
            requested_w?: number | null;
            /** Served W */
            served_w?: number | null;
            /** Shortfall W */
            shortfall_w?: number | null;
            /** Selected Zone Id */
            selected_zone_id?: string | null;
            /** Scanned Zone Ids */
            scanned_zone_ids?: string[];
            /** Priority Order */
            priority_order?: string[];
            /** Safety */
            safety?: {
                [key: string]: unknown;
            } | null;
            /** Edges */
            edges?: components["schemas"]["PowerEdge"][];
            /** Generated At */
            generated_at?: string | null;
            command?: components["schemas"]["CommandReceipt"] | null;
            model?: components["schemas"]["VisualizerModelStatus"] | null;
            replay?: components["schemas"]["VisualizerReplay"] | null;
            /** Policy */
            policy?: string | null;
        };
        /** HospitalDemoSensors */
        HospitalDemoSensors: {
            /** Current A */
            current_a?: number | null;
            /** Temperature C */
            temperature_c?: number | null;
            /** Input Voltage V */
            input_voltage_v?: number | null;
            /** Output Voltage V */
            output_voltage_v?: number | null;
            /** Cooling Ok */
            cooling_ok?: boolean | null;
        };
        /** HospitalDemoTransformerResponse */
        HospitalDemoTransformerResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Zone */
            zone: string;
            /** Rated Current A */
            rated_current_a?: number | null;
            sensors: components["schemas"]["HospitalDemoSensors"];
            diagnosis: components["schemas"]["HospitalDiagnosisResponse"];
            /** Energized */
            energized: boolean;
            /** Rfid Active */
            rfid_active?: boolean | null;
            /** Priority Rank */
            priority_rank?: number | null;
            activity?: components["schemas"]["VisualizerActivity"] | null;
            /** Loads */
            loads: components["schemas"]["VisualizerLoad"][];
        };
        /** HospitalDiagnosisResponse */
        HospitalDiagnosisResponse: {
            /** Code */
            code: string;
            /** Cause */
            cause: string;
            /** Severity */
            severity: string;
            /** Evidence */
            evidence: string[];
            /** Recommendation */
            recommendation: string;
            /** Hypotheses */
            hypotheses: components["schemas"]["DiagnosticHypothesisResponse"][];
            /** Status */
            status?: string | null;
            abstention?: components["schemas"]["DiagnosticAbstentionResponse"] | null;
            /** Missing */
            missing?: string[];
            /** Stale */
            stale?: string[];
        };
        /** HospitalRoom */
        HospitalRoom: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lighting Service */
            lighting_service: string;
            /** Led Bit */
            led_bit: number;
        };
        /** HospitalZone */
        HospitalZone: {
            /** Rooms */
            rooms: components["schemas"]["HospitalRoom"][];
        };
        /** ModelStatusResponse */
        ModelStatusResponse: {
            /** Ready */
            ready: boolean;
            /** Model Version */
            model_version: string;
            /** Model Type */
            model_type: string;
            /** Features */
            features: string[];
            /** Data Source */
            data_source: string;
            /** Evaluation */
            evaluation?: {
                [key: string]: unknown;
            };
            /** Fallback Reason */
            fallback_reason?: string | null;
        };
        /** PowerEdge */
        PowerEdge: {
            /** Id */
            id: string;
            /** From */
            from: string;
            /** To */
            to: string;
            /**
             * State
             * @enum {string}
             */
            state: "ENERGIZED" | "PENDING_RESTORATION" | "SHED" | "OPEN" | "UNKNOWN";
            /** Connected */
            connected: boolean;
            /** Commanded */
            commanded: boolean;
            /** Applied */
            applied: boolean;
            /** Requested W */
            requested_w: number;
            /** Served W */
            served_w: number;
            /**
             * Unit
             * @constant
             */
            unit: "W";
            /**
             * Provenance
             * @constant
             */
            provenance: "MODELED";
            /**
             * Physical
             * @enum {string}
             */
            physical: "NOT_CONNECTED" | "CONFIRMED";
            /** Reason */
            reason: string;
            observed?: components["schemas"]["PowerEdgeObservation"] | null;
        };
        /** PowerEdgeObservation */
        PowerEdgeObservation: {
            /** Output Voltage V */
            output_voltage_v?: number | null;
            /** Energized */
            energized?: boolean | null;
            /** Provenance */
            provenance: string;
            /** Diagnosis Status */
            diagnosis_status?: string | null;
            /** Note */
            note: string;
        };
        /** ReplayActionRequest */
        ReplayActionRequest: {
            /** Action */
            action: string;
        };
        /** ReplayActionResponse */
        ReplayActionResponse: {
            /** Running */
            running: boolean;
            /** Index */
            index: number;
            /** Length */
            length: number;
        };
        /** ReplaySnapshot */
        ReplaySnapshot: {
            /** Running */
            running: boolean;
            /** Index */
            index: number;
            /** Length */
            length: number;
        };
        /**
         * RfidEventType
         * @enum {string}
         */
        RfidEventType: "CARD_RECOGNIZED" | "UNKNOWN_CARD" | "DUPLICATE_SUPPRESSED";
        /**
         * RfidReaderStatus
         * @enum {string}
         */
        RfidReaderStatus: "NOT_CONNECTED" | "CONNECTED" | "ERROR";
        /** RfidScanRequest */
        RfidScanRequest: {
            /** Uid */
            uid: string;
            /** Event Id */
            event_id?: string | null;
        };
        /** RfidScanResponse */
        RfidScanResponse: {
            /** Accepted */
            accepted: boolean;
            /** Active Classroom Id */
            active_classroom_id?: string | null;
            /** Classroom Name */
            classroom_name?: string | null;
            /** Service Id */
            service_id?: string | null;
            event_type: components["schemas"]["RfidEventType"];
        };
        /** RunIdentity */
        RunIdentity: {
            /** Site Id */
            site_id: string;
            /** Run Id */
            run_id: string;
            /** Server Epoch */
            server_epoch: number;
            /** Config Hash */
            config_hash: string;
            /** Catalog Version */
            catalog_version: string;
            /** Policy Version */
            policy_version: string;
            /** Model Version */
            model_version: string;
            /** State Revision */
            state_revision: number;
            /** Observation Time */
            observation_time: string;
        };
        /** SafetySnapshot */
        SafetySnapshot: {
            /** Policy Version */
            policy_version: string;
            /** Status */
            status: string;
            /** Protected Requested W */
            protected_requested_w: number;
            /** Protected Served W */
            protected_served_w: number;
            /** Protected Shortfall W */
            protected_shortfall_w: number;
            /** Fallback Order */
            fallback_order: string[];
        };
        /** ScopeTotals */
        ScopeTotals: {
            /** Capacity W */
            capacity_w?: number | null;
            /** Requested W */
            requested_w: number;
            /** Served W */
            served_w: number;
        };
        /** ServiceSnapshot */
        ServiceSnapshot: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            tier: components["schemas"]["Tier"];
            /** Feeder */
            feeder: string;
            /** Watts */
            watts: number;
            /** Requested */
            requested: boolean;
            /** Modeled Served */
            modeled_served: boolean;
            /** Indicator Confirmed */
            indicator_confirmed?: boolean | null;
            /** Model Reason */
            model_reason: string;
        };
        /** SiteIdentityResponse */
        SiteIdentityResponse: {
            /** Run Id */
            run_id: string;
            /** Revision */
            revision: number;
            /** Profile */
            profile: string;
            /** Catalog Version */
            catalog_version: string;
        };
        /** SourceInfo */
        SourceInfo: {
            /**
             * Model
             * @default watt_budget
             * @constant
             */
            model: "watt_budget";
            /**
             * Limitations
             * @default Integer demand/capacity accounting; no AC power flow, thermal dynamics or protection physics
             */
            limitations: string;
            kind: components["schemas"]["SourceKind"];
            /** Capacity W */
            capacity_w: number;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "SIMULATED";
        /** StorageHealth */
        StorageHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "HEALTHY" | "DEGRADED";
            /** Degraded Reason */
            degraded_reason?: string | null;
        };
        /** SystemEvent */
        SystemEvent: {
            /** Event Id */
            event_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Timestamp */
            timestamp: string;
            /** Type */
            type: string;
            /** Description */
            description: string;
        };
        /** SystemSnapshot */
        SystemSnapshot: {
            contract: components["schemas"]["CrossRouteContract"];
            /**
             * Config Hash
             * @default
             */
            config_hash: string;
            /** Control Revision */
            control_revision: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Published Revision
             * @default 0
             */
            published_revision: number;
            source: components["schemas"]["SourceInfo"];
            /** Feeder Limits W */
            feeder_limits_w: {
                [key: string]: number;
            };
            /** Requested Mask */
            requested_mask: number;
            /** Modeled Mask */
            modeled_mask: number;
            /**
             * Proposed Mask
             * @default 0
             */
            proposed_mask: number;
            /** Indicator Command Mask */
            indicator_command_mask?: number | null;
            /** Indicator Confirmed Mask */
            indicator_confirmed_mask?: number | null;
            /** Indicator Mask */
            indicator_mask?: number | null;
            hardware_link: components["schemas"]["HardwareLinkStatus"];
            /** Services */
            services: components["schemas"]["ServiceSnapshot"][];
            zones?: components["schemas"]["FacilityZones"] | null;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["SystemEvent"][];
            fault_diagnosis?: components["schemas"]["FaultDiagnosis"] | null;
            /** Activity */
            activity?: {
                [key: string]: components["schemas"]["ActivitySnapshot"];
            };
            /** Model */
            model?: {
                [key: string]: unknown;
            };
            replay: components["schemas"]["ReplaySnapshot"];
            allocation: components["schemas"]["AllocationSnapshot"];
            site?: components["schemas"]["SiteIdentityResponse"] | null;
            /** Edges */
            edges?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * Tier
         * @enum {string}
         */
        Tier: "T1" | "T2" | "T3";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisualizerActivity */
        VisualizerActivity: {
            /**
             * State
             * @enum {string}
             */
            state: "ACTIVE" | "INACTIVE" | "UNKNOWN";
            /** Raw State */
            raw_state?: ("ACTIVE" | "INACTIVE" | "UNKNOWN") | null;
            /** Guard */
            guard?: string | null;
            /** Score */
            score: number | null;
            /** Reason */
            reason: string;
            /** Model Version */
            model_version: string;
            /** Evidence */
            evidence: {
                [key: string]: number | null;
            };
        };
        /** VisualizerLoad */
        VisualizerLoad: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Watts */
            watts?: number | null;
            /** Essential */
            essential?: boolean | null;
            /** Served */
            served: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** VisualizerModelStatus */
        VisualizerModelStatus: {
            /** Ready */
            ready: boolean;
            /** Model Version */
            model_version: string;
            /** Fallback Reason */
            fallback_reason?: string | null;
        };
        /** VisualizerReplay */
        VisualizerReplay: {
            /** Running */
            running: boolean;
            /** Index */
            index: number;
            /** Length */
            length: number;
            /** Step S */
            step_s: number;
        };
        /** WebSocketMessageEnvelope */
        WebSocketMessageEnvelope: {
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /**
             * Type
             * @constant
             */
            type: "snapshot";
            payload: components["schemas"]["SystemSnapshot"];
        };
        /** APIErrorResponse */
        APIErrorResponse: {
            /** Detail */
            detail: string | {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_v1_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    get_api_v1_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSnapshot"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    get_api_v1_model_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    get_api_v1_visualizers_classrooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomDemoResponse"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_visualizers_classrooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassroomDemoAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomDemoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    get_api_v1_hardware: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareStatusResponse"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_hardware_connect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayConnect"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_hardware_disconnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareStatusResponse"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    get_api_v1_visualizers_hospital: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HospitalDemoResponse"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_visualizers_hospital: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HospitalDemoAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HospitalDemoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_activity_observations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityObservationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityObservationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_replay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_rfid_scan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RfidScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RfidScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_simulation_capacity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapacityChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapacityChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_simulation_classroom_load: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassroomLoadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomLoadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_simulation_feeder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeederChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeederChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    get_api_v1_allocation_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationPolicyResponse"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    put_api_v1_allocation_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationPolicy"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationPolicyUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_studies_electrical: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElectricalInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectricalStudyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    post_api_v1_hardware_ack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HardwareAckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    get_api_v1_history_runs: {
        parameters: {
            query?: {
                site_id?: "campus";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryRunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    get_api_v1_history_records: {
        parameters: {
            query: {
                run_id: string;
                site_id?: "campus";
                kind?: ("event" | "decision" | "telemetry") | null;
                after?: number;
                limit?: number;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
}
