/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["HealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["GetSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Status */
        get: operations["ModelStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visualizers/classrooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Classroom Demo */
        get: operations["GetClassroomDemo"];
        put?: never;
        /** Act Classroom Demo */
        post: operations["ActClassroomDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visualizers/hospital": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hospital Demo */
        get: operations["GetHospitalDemo"];
        put?: never;
        /** Act Hospital Demo */
        post: operations["ActHospitalDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Activity Observation */
        post: operations["PostActivityObservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay Action */
        post: operations["ReplayAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rfid/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Rfid Scan */
        post: operations["ProcessRfidScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Capacity */
        post: operations["ChangeCapacity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/classroom-load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Classroom Load */
        post: operations["ChangeClassroomLoad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/feeder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Feeder */
        post: operations["ChangeFeeder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/allocation/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Allocation Policy */
        get: operations["ReadAllocationPolicy"];
        /** Change Allocation Policy */
        put: operations["ChangeAllocationPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/electrical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Electrical Study */
        post: operations["ElectricalStudy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hardware Ack */
        post: operations["HardwareAck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityObservationRequest */
        ActivityObservationRequest: {
            /** Classroom Id */
            classroom_id: string;
            /** Temperature C */
            temperature_c?: number | null;
            /** Humidity Pct */
            humidity_pct?: number | null;
            /** Co2 Ppm */
            co2_ppm?: number | null;
            /** Humidity Ratio */
            humidity_ratio?: number | null;
            /** Observed At */
            observed_at: string;
            /** Source */
            source: string;
        };
        /** ActivityObservationResponse */
        ActivityObservationResponse: {
            /** Accepted */
            accepted: boolean;
            /** Applied */
            applied: boolean;
            /** Revision */
            revision: number;
            activity: components["schemas"]["ActivitySnapshot"];
        };
        /** ActivitySnapshot */
        ActivitySnapshot: {
            /** State */
            state: string;
            /** Score */
            score?: number | null;
            /** Reason */
            reason: string;
            /** Source */
            source?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Model Version */
            model_version: string;
            /** Priority */
            priority: string;
            /** Evidence */
            evidence?: {
                [key: string]: number | null;
            } | null;
            /** Raw State */
            raw_state?: string | null;
            /** Guard */
            guard?: string | null;
        };
        /** AllocationPolicy */
        AllocationPolicy: {
            /**
             * Name
             * @default activity_first
             * @enum {string}
             */
            name: "activity_first" | "water_first";
            /**
             * Version
             * @default allocation-v1
             * @constant
             */
            version: "allocation-v1";
            /**
             * Fairness Weight
             * @default 0
             */
            fairness_weight: number;
            /**
             * Switching Penalty
             * @default 1
             */
            switching_penalty: number;
        };
        /** AllocationSnapshot */
        AllocationSnapshot: {
            /** Explanation */
            explanation?: {
                [key: string]: unknown;
            };
            /** Objective */
            objective: string;
            /** Critical Shortfall W */
            critical_shortfall_w: number;
            /** Served W */
            served_w: number;
            /** Baseline Mask */
            baseline_mask: number;
            safety?: components["schemas"]["SafetySnapshot"] | null;
        };
        /** CapacityChangeRequest */
        CapacityChangeRequest: {
            /** Capacity W */
            capacity_w: number;
        };
        /** CapacityChangeResponse */
        CapacityChangeResponse: {
            /** Accepted */
            accepted: boolean;
            /** New Capacity W */
            new_capacity_w: number;
            /** Control Revision */
            control_revision: number;
        };
        /** ClassroomDemoAction */
        ClassroomDemoAction: {
            /**
             * Action
             * @enum {string}
             */
            action: "scan" | "unscan" | "set_capacity" | "normal" | "overload" | "reset" | "replay_pause" | "replay_resume" | "replay_step";
            /** Classroom Id */
            classroom_id?: ("CR1" | "CR2" | "CR3") | null;
            /** Capacity W */
            capacity_w?: number | null;
        };
        /** ClassroomInfo */
        ClassroomInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Service Id */
            service_id: string;
            /** Rfid Card Registered */
            rfid_card_registered: boolean;
            /** Led Bit */
            led_bit: number;
            /** Load Event Active */
            load_event_active: boolean;
        };
        /** ClassroomLoadRequest */
        ClassroomLoadRequest: {
            /** Classroom Id */
            classroom_id: string;
            /** Active */
            active: boolean;
        };
        /** ClassroomLoadResponse */
        ClassroomLoadResponse: {
            /** Accepted */
            accepted: boolean;
            /** Classroom Id */
            classroom_id: string;
            /** Load Event Active */
            load_event_active: boolean;
        };
        /** ClassroomZone */
        ClassroomZone: {
            /** Active Classroom Id */
            active_classroom_id?: string | null;
            /** Recent Rfid Scan */
            recent_rfid_scan?: string | null;
            /** @default NOT_CONNECTED */
            rfid_reader_status: components["schemas"]["RfidReaderStatus"];
            /** Classrooms */
            classrooms: components["schemas"]["ClassroomInfo"][];
        };
        /** CrossRouteContract */
        CrossRouteContract: {
            identity: components["schemas"]["RunIdentity"];
            campus_totals?: components["schemas"]["ScopeTotals"] | null;
            /**
             * Zone Totals
             * @default {}
             */
            zone_totals: {
                [key: string]: components["schemas"]["ScopeTotals"];
            };
        };
        /** ElectricalInput */
        ElectricalInput: {
            /**
             * Topology Version
             * @default radial-400v-v1
             * @constant
             */
            topology_version: "radial-400v-v1";
            /**
             * Balanced
             * @default true
             */
            balanced: boolean;
            /**
             * Load A W
             * @default 6000
             */
            load_a_w: number;
            /**
             * Load B W
             * @default 8000
             */
            load_b_w: number;
            /**
             * Source On
             * @default true
             */
            source_on: boolean;
            /**
             * Feeder A Closed
             * @default true
             */
            feeder_a_closed: boolean;
            /**
             * Feeder B Closed
             * @default true
             */
            feeder_b_closed: boolean;
            /**
             * Power Factor
             * @default 0.95
             */
            power_factor: number;
            /**
             * Resistance Ohm
             * @default 0.04
             */
            resistance_ohm: number;
            /**
             * Reactance Ohm
             * @default 0.015
             */
            reactance_ohm: number;
        };
        /** ElectricalResult */
        ElectricalResult: {
            /**
             * Mode
             * @default balanced_ac_study
             * @constant
             */
            mode: "balanced_ac_study";
            /**
             * Topology Version
             * @default radial-400v-v1
             */
            topology_version: string;
            /** Engine */
            engine: string;
            /** Engine Version */
            engine_version?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "converged" | "deenergized" | "failed" | "unavailable";
            /** Converged */
            converged: boolean;
            /**
             * Restoration Authorized
             * @default false
             * @constant
             */
            restoration_authorized: false;
            /** Observed At */
            observed_at: string;
            inputs: components["schemas"]["ElectricalInput"];
            /** Units */
            units: {
                [key: string]: string;
            };
            /** Buses */
            buses: {
                [key: string]: {
                    [key: string]: number | boolean | null;
                };
            };
            /** Branches */
            branches: {
                [key: string]: {
                    [key: string]: number | boolean | null;
                };
            };
            /** Source P W */
            source_p_w?: number | null;
            /** Source Q Var */
            source_q_var?: number | null;
            /** Loss W */
            loss_w?: number | null;
            /** Power Balance Residual W */
            power_balance_residual_w?: number | null;
            /** Reason */
            reason?: string | null;
            /**
             * Provenance
             * @default SIMULATED_AC_SOLVER; synthetic engineering parameters
             */
            provenance: string;
        };
        /** ElectricalStudyResponse */
        ElectricalStudyResponse: {
            /** Site */
            site: {
                [key: string]: unknown;
            };
            result: components["schemas"]["ElectricalResult"];
            /** Diagnosis */
            diagnosis: {
                [key: string]: unknown;
            };
        };
        /** FacilityZones */
        FacilityZones: {
            hospital: components["schemas"]["HospitalZone"];
            classroom: components["schemas"]["ClassroomZone"];
        };
        /** FaultDiagnosis */
        FaultDiagnosis: {
            /** Has Fault */
            has_fault: boolean;
            /** Diagnosis */
            diagnosis: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Hypotheses */
            hypotheses?: {
                [key: string]: unknown;
            }[];
            /** Affected Assets */
            affected_assets?: string[];
            /** Supply Constraint */
            supply_constraint?: string | null;
        };
        /** FeederChangeRequest */
        FeederChangeRequest: {
            /** Feeder */
            feeder: string;
            /** Available */
            available: boolean;
        };
        /** FeederChangeResponse */
        FeederChangeResponse: {
            /** Accepted */
            accepted: boolean;
            /** Feeder */
            feeder: string;
            /** Available */
            available: boolean;
            /** Control Revision */
            control_revision: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareAckRequest */
        HardwareAckRequest: {
            /** Device Boot */
            device_boot: string;
            /** Sequence */
            sequence: number;
            /** Session */
            session: string;
            /** Confirmed Mask */
            confirmed_mask: number;
            /** Provenance */
            provenance: string;
        };
        /** HardwareAckResponse */
        HardwareAckResponse: {
            /** Accepted */
            accepted: boolean;
        };
        /**
         * HardwareLinkStatus
         * @enum {string}
         */
        HardwareLinkStatus: "NOT_CONNECTED" | "CONNECTED" | "ERROR";
        /** HealthResponse */
        HealthResponse: {
            /** Control Loop */
            control_loop?: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Application */
            application: string;
        };
        /** HospitalDemoAction */
        HospitalDemoAction: {
            /** Action */
            action?: ("scan" | "unscan" | "set_capacity" | "normal" | "overload" | "reset" | "replay_pause" | "replay_resume" | "replay_step") | null;
            /** Zone Id */
            zone_id?: ("ICU" | "Theatre" | "Wards") | null;
            /** Capacity W */
            capacity_w?: number | null;
            /** Scenario */
            scenario?: ("normal" | "overload" | "cooling_failure" | "upstream_loss" | "missing_sensor") | null;
        };
        /** HospitalRoom */
        HospitalRoom: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lighting Service */
            lighting_service: string;
            /** Led Bit */
            led_bit: number;
        };
        /** HospitalZone */
        HospitalZone: {
            /** Rooms */
            rooms: components["schemas"]["HospitalRoom"][];
        };
        /** ModelStatusResponse */
        ModelStatusResponse: {
            /** Ready */
            ready: boolean;
            /** Model Version */
            model_version: string;
            /** Model Type */
            model_type: string;
            /** Features */
            features: string[];
            /** Data Source */
            data_source: string;
            /** Evaluation */
            evaluation?: {
                [key: string]: unknown;
            };
            /** Fallback Reason */
            fallback_reason?: string | null;
        };
        /** ReplayActionRequest */
        ReplayActionRequest: {
            /** Action */
            action: string;
        };
        /** ReplayActionResponse */
        ReplayActionResponse: {
            /** Running */
            running: boolean;
            /** Index */
            index: number;
            /** Length */
            length: number;
        };
        /** ReplaySnapshot */
        ReplaySnapshot: {
            /** Running */
            running: boolean;
            /** Index */
            index: number;
            /** Length */
            length: number;
        };
        /**
         * RfidEventType
         * @enum {string}
         */
        RfidEventType: "CARD_RECOGNIZED" | "UNKNOWN_CARD" | "DUPLICATE_SUPPRESSED";
        /**
         * RfidReaderStatus
         * @enum {string}
         */
        RfidReaderStatus: "NOT_CONNECTED" | "CONNECTED" | "ERROR";
        /** RfidScanRequest */
        RfidScanRequest: {
            /** Uid */
            uid: string;
            /** Event Id */
            event_id?: string | null;
        };
        /** RfidScanResponse */
        RfidScanResponse: {
            /** Accepted */
            accepted: boolean;
            /** Active Classroom Id */
            active_classroom_id?: string | null;
            /** Classroom Name */
            classroom_name?: string | null;
            /** Service Id */
            service_id?: string | null;
            event_type: components["schemas"]["RfidEventType"];
        };
        /** RunIdentity */
        RunIdentity: {
            /** Site Id */
            site_id: string;
            /** Run Id */
            run_id: string;
            /** Server Epoch */
            server_epoch: number;
            /** Config Hash */
            config_hash: string;
            /** Catalog Version */
            catalog_version: string;
            /** Policy Version */
            policy_version: string;
            /** Model Version */
            model_version: string;
            /** State Revision */
            state_revision: number;
            /** Observation Time */
            observation_time: string;
        };
        /** SafetySnapshot */
        SafetySnapshot: {
            /** Policy Version */
            policy_version: string;
            /** Status */
            status: string;
            /** Protected Requested W */
            protected_requested_w: number;
            /** Protected Served W */
            protected_served_w: number;
            /** Protected Shortfall W */
            protected_shortfall_w: number;
            /** Fallback Order */
            fallback_order: string[];
        };
        /** ScopeTotals */
        ScopeTotals: {
            /** Capacity W */
            capacity_w?: number | null;
            /** Requested W */
            requested_w: number;
            /** Served W */
            served_w: number;
        };
        /** ServiceSnapshot */
        ServiceSnapshot: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            tier: components["schemas"]["Tier"];
            /** Feeder */
            feeder: string;
            /** Watts */
            watts: number;
            /** Requested */
            requested: boolean;
            /** Modeled Served */
            modeled_served: boolean;
            /** Indicator Confirmed */
            indicator_confirmed?: boolean | null;
            /** Model Reason */
            model_reason: string;
        };
        /** SourceInfo */
        SourceInfo: {
            /**
             * Model
             * @default watt_budget
             * @constant
             */
            model: "watt_budget";
            /**
             * Limitations
             * @default Integer demand/capacity accounting; no AC power flow, thermal dynamics or protection physics
             */
            limitations: string;
            kind: components["schemas"]["SourceKind"];
            /** Capacity W */
            capacity_w: number;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "SIMULATED";
        /** SystemEvent */
        SystemEvent: {
            /** Timestamp */
            timestamp: string;
            /** Type */
            type: string;
            /** Description */
            description: string;
        };
        /** SystemSnapshot */
        SystemSnapshot: {
            contract: components["schemas"]["CrossRouteContract"];
            /**
             * Config Hash
             * @default
             */
            config_hash: string;
            /** Control Revision */
            control_revision: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Published Revision
             * @default 0
             */
            published_revision: number;
            source: components["schemas"]["SourceInfo"];
            /** Feeder Limits W */
            feeder_limits_w: {
                [key: string]: number;
            };
            /** Requested Mask */
            requested_mask: number;
            /** Modeled Mask */
            modeled_mask: number;
            /**
             * Proposed Mask
             * @default 0
             */
            proposed_mask: number;
            /** Indicator Command Mask */
            indicator_command_mask?: number | null;
            /** Indicator Confirmed Mask */
            indicator_confirmed_mask?: number | null;
            /** Indicator Mask */
            indicator_mask?: number | null;
            hardware_link: components["schemas"]["HardwareLinkStatus"];
            /** Services */
            services: components["schemas"]["ServiceSnapshot"][];
            zones?: components["schemas"]["FacilityZones"] | null;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["SystemEvent"][];
            fault_diagnosis?: components["schemas"]["FaultDiagnosis"] | null;
            /** Activity */
            activity?: {
                [key: string]: components["schemas"]["ActivitySnapshot"];
            };
            /** Model */
            model?: {
                [key: string]: unknown;
            };
            replay: components["schemas"]["ReplaySnapshot"];
            allocation: components["schemas"]["AllocationSnapshot"];
            /** Site */
            site?: {
                [key: string]: unknown;
            } | null;
            /** Edges */
            edges?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * Tier
         * @enum {string}
         */
        Tier: "T1" | "T2" | "T3";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebSocketMessageEnvelope */
        WebSocketMessageEnvelope: {
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /** Type */
            type: string;
            payload: components["schemas"]["SystemSnapshot"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    GetSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSnapshot"];
                };
            };
        };
    };
    ModelStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
        };
    };
    GetClassroomDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ActClassroomDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassroomDemoAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    GetHospitalDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ActHospitalDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HospitalDemoAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    PostActivityObservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityObservationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityObservationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ReplayAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ProcessRfidScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RfidScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RfidScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ChangeCapacity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapacityChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapacityChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ChangeClassroomLoad: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassroomLoadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomLoadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ChangeFeeder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeederChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeederChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ReadAllocationPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ChangeAllocationPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationPolicy"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ElectricalStudy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElectricalInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectricalStudyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    HardwareAck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HardwareAckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareAckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
